export const productsData = [
  { title: "Rack and Pinion Actuator", url: "/products/rack-and-pinion-actuator" },
  { title: "Scotch Yoke Actuatorr", url: "/products/scotch-yoke-actuatorr" },
  { title: "PTL Series Electrical Actuator", url: "/products/ptl-series-electrical-actuator" },
  { title: "PVQ explosion proof electric actuator", url: "/products/pvq-explosion-proof-electric-actuator" },
  { title: "PHQ explosion proof electric actuator", url: "/products/phq-explosion-proof-electric-actuator" },
  { title: "aum multi turn electrical actuator", url: "/products/aum-multi-turn-electrical-actuator" },
  { title: "Pneumatic Rotary Actuator Operated 3 Pcs Ball Valve", url: "/products/pneumatic-rotary-actuator-operated-3-pcs-ball-valve" },
  { title: "Pneumatic Rotary Actuator Operated 2 Pcs Ball Valve", url: "/products/pneumatic-rotary-actuator-operated-2-pcs-ball-valve" },
  { title: "Pneumatic Rotary Actuator Operated 3 Way / 4 Way Ball Valve Screwed End / Flanged End.", url: "/products/pneumatic-rotary-actuator-operated-3-way-4-way-ball-valve-screwed-end-flanged-end" },
  { title: "Pneumatic Rotary Actuator Operated Wafer Type Ball Valver", url: "/products/pneumatic-rotary-actuator-operated-wafer-type-ball-valver" },
  { title: "Pneumatic Rotary Actuator Operated FEP / PFA Lined Ball Valve", url: "/products/pneumatic-rotary-actuator-operated-fep-pfa-lined-ball-valve" },
  { title: "Pneumatic Rotary Actuator Operated UPVC Ball Valve", url: "/products/pneumatic-rotary-actuator-operated-upvc-ball-valve" },
  { title: "Pneumatic Rotary Actuator Operated PP Ball Valve", url: "/products/pneumatic-rotary-actuator-operated-pp-ball-valve" },
  { title: "Pneumatic Actuator Operated Rubber Lined Butterfly Valve", url: "/products/pneumatic-actuator-operated-rubber-lined-butterfly-valve" },
  { title: "Pneumatic Actuator Operated Rubber Lined Double Flange Type Butterfly Valve", url: "/products/pneumatic-actuator-operated-rubber-lined-double-flange-type-butterfly-valve" },
  { title: "Pneumatic Actuator Operated Rubber Lined Lug Type Butterfly Valve", url: "/products/pneumatic-actuator-operated-rubber-lined-lug-type-butterfly-valve" },
  { title: "Pneumatic Actuator Operated Spherical Disc Valve 150# & 300#", url: "/products/pneumatic-actuator-operated-spherical-disc-valve-150-300" },
  { title: "Pneumatic Actuator Operated FEP / PFA Lined Butterfly Valve", url: "/products/pneumatic-actuator-operated-fep-pfa-lined-butterfly-valve" },
  { title: "Pneumatic Actuator Operated PTFE Lined Butterfly Valve", url: "/products/pneumatic-actuator-operated-ptfe-lined-butterfly-valve" },
  { title: "Pneumatic Actuator Operated Aluminium Pressure Die Cast Butterly Valve", url: "/products/pneumatic-actuator-operated-aluminium-pressure-die-cast-butterly-valve" },
  { title: "Pneumatic Actuator Operated Wafer Type Metal Seated Damper Valve", url: "/products/pneumatic-actuator-operated-wafer-type-metal-seated-damper-valve" },
  { title: "Pneumatic Actuator Operated Double Flange Fabricated Damper Valve", url: "/products/pneumatic-actuator-operated-double-flange-fabricated-damper-valve" },
  { title: "Pneumatic Actuator Operated UPVC Wafer Type Butterfly Valve", url: "/products/pneumatic-actuator-operated-upvc-wafer-type-butterfly-valve" },
  { title: "Pneumatic Actuator Operated Wafer Type / TC End Butterfly Valve For Pharma Application.", url: "/products/pneumatic-actuator-operated-wafer-type-tc-end-butterfly-valve-for-pharma-application" },
  { title: "Electrical On/off, Modulating, Intergral Starter UPVC Ball Valve", url: "/products/electrical-onoff-modulating-integral-starter-upvc-ball-valve" },
  { title: "Motorized 2 Pcs Ball Valve Flanged End ASA 150#/300#", url: "/products/motorized-2-pcs-ball-valve-flanged-end-asa-150-300" },
  { title: "Motorized 2 Pcs FEP / PFA Lined Ball Valve Flanged End", url: "/products/motorized-2-pcs-fep-pfa-lined-ball-valve-flanged-end" },
  { title: "Motorized 3 WAY / 4 WAY BALL VALVE", url: "/products/motorized-3-way-4-way-ball-valve" },
  { title: "Motorized 3 pcs ball valve Screwed end / Flanged end ASA 150# / 300#", url: "/products/motorized-3-pcs-ball-valve-screwed-end-flanged-end-asa-150-300" },
  { title: "Motorized PP Ball Valve", url: "/products/motorized-pp-ball-valve" },
  { title: "Motorized Wafer type Ball Valve", url: "/products/motorized-wafer-type-ball-valve" },
  { title: "Elecrical On/off, Moudlating And Intergral Starter FEP / PFA Lined Butterfly Valve", url: "/products/electrical-onoff-modulating-integral-starter-fep-pfa-lined-butterfly-valve" },
  { title: "Electrical On/Off, Modulating And Integral Starter Spherical Disc Valve 150# & 300#", url: "/products/electrical-onoff-modulating-integral-starter-spherical-disc-valve-150-300" },
  { title: "Motorized Double Flange Butterfly Valve", url: "/products/motorized-double-flange-butterfly-valve" },
  { title: "Motorized Wafer type Butterfly Valve", url: "/products/motorized-wafer-type-butterfly-valve" },
  { title: "Motorize Rubber Seated Lug type Butterfly Valve", url: "/products/motorized-rubber-seated-lug-type-butterfly-valve" },
  { title: "Electrical ON/OFF, Modulating And Integral Started PTFE Lined Butterfly Valve", url: "/products/electrical-onoff-modulating-integral-starter-ptfe-lined-butterfly-valve" },
  { title: "Modulating and Integral Starter Double Flange Fabricated Damper Valve", url: "/products/modulating-integral-starter-double-flange-fabricated-damper-valve" },
  { title: "Motorized aluminium butterfly valve", url: "/products/motorized-aluminium-butterfly-valve" },
  { title: "Motorized UPVC Wafer Type Butterfly Valve", url: "/products/motorized-upvc-wafer-type-butterfly-valve" },
  { title: "2 2 way pilot operated diaphragm type solenoid valve", url: "/products/2-2-way-pilot-operated-diaphragm-type-solenoid-valve" },
  { title: "2/2 Way Semi lift Diaphragm Solenoid Valve", url: "/products/2-2-way-semi-lift-diaphragm-solenoid-valve" },
  { title: "2/2 Way Pilot operated piston type steam solenoid valve", url: "/products/2-2-way-pilot-operated-piston-type-steam-solenoid-valve" },
  { title: "Aluminium Flame Proof Type Solenoid Valvese", url: "/products/aluminium-flame-proof-type-solenoid-valvese" },
  { title: "2/2 Way Direct Acting Solenoid Valve", url: "/products/2-2-way-direct-acting-solenoid-valve" },
  { title: "2/2 Way Pneumatic Single & Double Acting Operated Angle Type On/Off Control Valve", url: "/products/2-2-way-pneumatic-single-double-acting-operated-angle-type-onoff-control-valve" },
  { title: "Model APL2N (Micro Limit Switches)", url: "/products/model-apl2n-micro-limit-switches" },
  { title: "Model APL3N (Micro Limit Switches)", url: "/products/model-apl3n-micro-limit-switches" },
  { title: "Model APL4N (Micro Limit Switches)", url: "/products/model-apl4n-micro-limit-switches" },
  { title: "Model ITS 100 (Micro Limit Switches)", url: "/products/model-its-100-micro-limit-switches" },
  { title: "Yt-1000 Electro Pneumatic Valve Positioner", url: "/products/yt-1000-electro-pneumatic-valve-positioner" },
  { title: "L8A-100 Electro Pneumatic Valve Positioner", url: "/products/l8a-100-electro-pneumatic-valve-positioner" },
  { title: "PSP-25 Series Smart Positioner", url: "/products/psp-25-series-smart-positioner" },
  { title: "Quarter Turn Manual Over Ride / Gear Box", url: "/products/quarter-turn-manual-over-ride-gear-box" },
  { title: "Air Filter Regulator", url: "/products/air-filter-regulator" },
  { title: "5/2 Way Single / Double Coil", url: "/products/5-2-way-single-double-coil" },
  { title: "3/2 Way Single / Double Coil", url: "/products/3-2-way-single-double-coil" },
  { title: "Electrical ON/OFF, Modulating And ntegral Starter Wafer Type Metal Seated Damper Valve", url: "/products/electrical-onoff-modulating-integral-starter-wafer-type-metal-seated-damper-valve" },
  { title: "Electrical on/off, modulating and integral starter Wafer Type / TC End Butter Valve For Pharma Application", url: "/products/electrical-onoff-modulating-integral-starter-wafer-type-tc-end-butter-valve-for-pharma-application" }
];